name: Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Set up safe directory
      run: git config --global --add safe.directory 'C:/backend-runner/_work/MasterThesisBackend/MasterThesisBackend'

    - name: Wait for a few seconds
      run: Start-Sleep -Seconds 10

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Clear npm cache
      run: npm cache clean --force    

    - name: Check Node.js and npm version
      run: |
        echo "Node.js version: $(node -v)"
        echo "npm version: $(npm -v)"
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install Functions Dependencies
      run: npm ci --prefix functions

    - name: Set up Google Cloud Credentials
      shell: powershell
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        $serviceAccountKey = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"))
        Set-Content -Path "$env:GITHUB_WORKSPACE/service-account.json" -Value $serviceAccountKey
        $env:GOOGLE_APPLICATION_CREDENTIALS="$env:GITHUB_WORKSPACE/service-account.json"
        Write-Host "Service account JSON written to $env:GITHUB_WORKSPACE/service-account.json"

    - name: Set Firebase Project
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        firebase use --add satish-masterthesis --alias default --debug

    - name: Deploy to Firebase Functions
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: firebase deploy --only functions --debug
