name: Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Set up safe directory
      run: git config --global --add safe.directory 'C:/backend-runner/_work/MasterThesisBackend/MasterThesisBackend'

    - name: Wait for a few seconds
      run: Start-Sleep -Seconds 10

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Update to use Node.js 18

    - name: Clear npm cache
      run: npm cache clean --force    

    - name: Check Node.js and npm version
      run: |
        echo "Node.js version: $(node -v)"
        echo "npm version: $(npm -v)"
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install Functions Dependencies with verbose logging
      run: npm ci --prefix functions --loglevel verbose

    - name: Set up GOOGLE_APPLICATION_CREDENTIALS
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > ${{ runner.temp }}/service-account.json

    - name: Set Firebase Project
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/service-account.json
      run: firebase use --add satish-masterthesis --alias default --debug

    - name: Deploy to Firebase Functions with verbose logging
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/service-account.json
      run: firebase deploy --only functions --debug
