name: Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Set up safe directory
      run: git config --global --add safe.directory 'C:/backend-runner/_work/MasterThesisBackend/MasterThesisBackend'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate to Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        $firebaseServiceAccount = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:FIREBASE_SERVICE_ACCOUNT))
        $firebaseServiceAccount | Out-File -FilePath $env:USERPROFILE/firebase-service-account.json -Encoding ascii
        gcloud auth activate-service-account --key-file=$env:USERPROFILE/firebase-service-account.json
      shell: powershell

    - name: Install Dependencies
      run: npm install

    - name: Deploy to Firebase Functions
      run: firebase deploy --only functions
