name: Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up safe directory
      run: git config --global --add safe.directory 'C:/backend-runner/_work/MasterThesisBackend/MasterThesisBackend'

    - name: Wait for a few seconds
      run: Start-Sleep -Seconds 10

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Clear npm cache
      run: npm cache clean --force    

    - name: Check Node.js and npm version
      run: |
       echo "Node.js version: $(node -v)"
       echo "npm version: $(npm -v)"

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    # If the secret contains the Base64-encoded content
    - name: Create service account file from secret
      run: echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 -d > $env:GITHUB_WORKSPACE/service-account.json
      shell: powershell

    - name: Set environment variable for service account file path
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/service-account.json" >> $GITHUB_ENV

    - name: Install Functions Dependencies
      run: npm ci --prefix functions --loglevel verbose

    - name: Set Firebase Project
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        firebase use --add satish-masterthesis --alias default --debug
      shell: powershell

    - name: Deploy to Firebase Functions
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
      run: firebase deploy --only functions --debug
      shell: powershell
