name: Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Set up safe directory
      run: git config --global --add safe.directory 'C:/backend-runner/_work/MasterThesisBackend/MasterThesisBackend'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install Dependencies
      run: npm install

    - name: Authenticate to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: echo "${FIREBASE_TOKEN}" | firebase auth:ci-login

    - name: Set Firebase Project
      run: firebase use --add satish-masterthesis --alias default

    - name: Deploy to Firebase Functions
      run: firebase deploy --only functions
