name: Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Set up safe directory
      run: git config --global --add safe.directory 'C:/backend-runner/_work/MasterThesisBackend/MasterThesisBackend'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install Root Dependencies
      run: npm install

    - name: Install Functions Dependencies
      run: npm install --prefix functions

    - name: Set Firebase Project
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        firebase use --add satish-masterthesis --alias default --token ${{ secrets.FIREBASE_TOKEN }}
        firebase use default

    - name: Deploy to Firebase Functions
      run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
