name: Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Set up safe directory
      run: powershell -command "git config --global --add safe.directory 'C:/backend-runner/_work/MasterThesisBackend/MasterThesisBackend'"

    - name: Wait for a few seconds
      run: powershell -command "Start-Sleep -Seconds 10"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Clear npm cache
      run: powershell -command "npm cache clean --force"    

    - name: Check Node.js and npm version
      run: |
       echo "Node.js version: $(node -v)"
       echo "npm version: $(npm -v)"
      
    - name: Install Firebase CLI
      run: powershell -command "npm install -g firebase-tools"

    - name: Install Functions Dependencies
      run: powershell -command "npm ci --prefix functions --loglevel verbose"

    - name: Set up Google Cloud Credentials
      run: |
        $serviceAccountKey = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"))
        Set-Content -Path "$env:GITHUB_WORKSPACE/service-account.json" -Value $serviceAccountKey
        $env:GOOGLE_APPLICATION_CREDENTIALS="$env:GITHUB_WORKSPACE/service-account.json"
        Write-Host "Service account JSON written to $env:GITHUB_WORKSPACE/service-account.json"
      shell: powershell

    - name: Set Firebase Project
      run: powershell -command "firebase use --add satish-masterthesis --alias default --debug"

    - name: Deploy to Firebase Functions
      run: powershell -command "firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }} --debug"
